export const SUBTAITORU_ROOT_ID = "subtaitoru-react-root";
export const QUIZ_ROOT_ID = "subtaitoru-react-root-quiz";

export const PLATFORMS = {
  YOUTUBE: "youtube",
  NETFLIX: "netflix",
  AMAZON_PRIME: "amazon",
} as const;

export const API_ENDPOINTS = {
  TRANSLATION: `${process.env.TRANSLATION_API_URL}?keyword=`,
};

export const DEFAULT_FONT_SIZE = "24px";

export const JAPANESE_SAVED_WORDS = "words-jp";

// Replace this with your actual Google Form URL
export const BUG_REPORT_FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLSc7wDpMGIqZ0mYrlCUgVAYwC_r_HvDL_DaizJ6ks5z3mw9zLQ/viewform?usp=header";

// Common English words categorized by difficulty
export const COMMON_ENGLISH_WORDS = {
  BASIC: [
    "time",
    "person",
    "year",
    "way",
    "day",
    "thing",
    "man",
    "world",
    "life",
    "hand",
    "part",
    "child",
    "eye",
    "woman",
    "place",
    "work",
    "week",
    "case",
    "point",
    "group",
    "number",
    "room",
    "fact",
    "idea",
    "water",
    "money",
    "month",
    "book",
    "line",
    "system",
    "family",
    "question",
    "story",
    "country",
    "example",
    "school",
    "night",
    "word",
    "business",
    "issue",
    "side",
    "kind",
    "head",
    "house",
    "service",
    "friend",
    "father",
    "power",
    "hour",
    "game",
  ],
  INTERMEDIATE: [
    "development",
    "position",
    "interest",
    "education",
    "society",
    "activity",
    "organization",
    "experience",
    "environment",
    "community",
    "population",
    "production",
    "information",
    "direction",
    "technology",
    "management",
    "movement",
    "solution",
    "association",
    "discussion",
    "collection",
    "competition",
    "conference",
    "performance",
    "operation",
    "opportunity",
    "recognition",
    "communication",
    "conversation",
    "celebration",
    "imagination",
    "introduction",
    "understanding",
    "relationship",
    "description",
    "distribution",
    "independence",
    "entertainment",
    "improvement",
    "temperature",
    "investment",
    "responsibility",
    "knowledge",
    "permission",
    "statement",
  ],
  ADVANCED: [
    "philosophy",
    "hypothesis",
    "perspective",
    "phenomenon",
    "circumstance",
    "appreciation",
    "interpretation",
    "characteristic",
    "concentration",
    "consciousness",
    "establishment",
    "participation",
    "investigation",
    "professional",
    "recommendation",
    "significance",
    "contribution",
    "achievement",
    "determination",
    "observation",
    "requirement",
    "maintenance",
    "institution",
    "intelligence",
    "demonstration",
    "application",
    "consideration",
    "opportunity",
    "presentation",
    "administration",
    "organization",
    "responsibility",
    "understanding",
    "development",
    "performance",
    "conversation",
    "environment",
    "relationship",
    "information",
    "communication",
  ],
} as const;
