name: "🐛 Bug Report"
description: "Use this template to report a bug or issue."
title: "[BUG] Brief description of the issue"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report

        Please provide details about the bug. This helps us understand and resolve the issue.

  - type: textarea
    id: bug_description
    attributes:
      label: "Bug Description"
      description: "Describe the bug you're experiencing."
      placeholder: "Brief description of the bug (e.g., the application crashes when...)"

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide the steps to reproduce the issue."
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. See error"

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe the expected behavior..."

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Describe what actually happened..."

  - type: textarea
    id: affected_files
    attributes:
      label: "Affected Files"
      description: "List the files or modules you think may be affected."
      placeholder: "src/file1.py, src/file2.js"

  - type: dropdown
    id: is_regression
    attributes:
      label: "Is this a regression?"
      description: "Did this issue start happening after a recent update?"
      options:
        - "Yes"
        - "No"
        - "Unsure"

  - type: markdown
    attributes:
      value: |
        **Thank you for reporting this bug! We’ll address it as soon as possible.**
