name: "Report A Bug 🐛"
description: "Please fill out the form below to report a bug in Subtaitoru."
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## Found a problem? Let us know!

  - type: textarea
    id: what_happened
    attributes:
      label: "What happened?"
      description: "Describe the problem"
      placeholder: "The subtitles don't show up"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Describe the steps to reproduce the problem"
      placeholder: |
        1. Opened YouTube
        2. Played a video
        3. Clicked the extension
    validations:
      required: true

  - type: textarea
    id: screenshot_link
    attributes:
      label: "📸 Screenshot"
      description: "Upload your screenshot to imgur.com and paste the link here"
      placeholder: "https://imgur.com/..."

  - type: dropdown
    id: browser
    attributes:
      label: "Your browser"
      options:
        - "Google Chrome"
        - "Microsoft Edge"
        - "Brave"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: "How often does it happen?"
      options:
        - "Every time"
        - "Sometimes"
        - "Just once"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thanks for helping! 🙏
